package DengueReportSystem;

import java.awt.Font;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

public class GUIHomePage extends javax.swing.JFrame {
    //Variable for GUI draggable
    private int mousepX, mousepY;
    //Variable for deep cloning
    private ListCloner listCloner;
    
    //List to store the original data source
    //and data source that added Pahang(Total)
    private List<Area> orgDataSource, newAreaList;
    
    public GUIHomePage(List<Area> orgDataSource) {
        try{
            //Initializing
            initComponents();
            listCloner = new ListCloner();
            
            //Do not need deep clone
            //because this list will only be used for passing to next GUI
            this.orgDataSource = orgDataSource;

            //Question 2
            newAreaList = createNewAreaList.apply(orgDataSource);

            //Question 1
            bindAllDengueCasesDataToTable(newAreaList);
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    /****************Question 2*******************/
    //Calculate total cases for a year
    private BiFunction<List<Area>,Integer,Integer> calcSumForAYear =(dataSource,year)->{
        return dataSource.stream()
                .map(area->area.getCasesList().get(year))
                .mapToInt(Integer::intValue)
                .sum();
    };
    
    //Create a map for storing the data(Total cases for each year)
    private HexaFunc<Integer, Integer, Integer, Integer, Integer, Integer, LinkedHashMap<Integer, Integer>> 
        createSumPerYearMap = (cases14, cases15, cases16, cases17, cases18, cases19) -> {
            //Create a map
            LinkedHashMap<Integer, Integer> sumPerYearMap = new LinkedHashMap<>();
            
            //add the key and value into the map
            sumPerYearMap.put(2014, cases14);
            sumPerYearMap.put(2015, cases15);
            sumPerYearMap.put(2016, cases16);
            sumPerYearMap.put(2017, cases17);
            sumPerYearMap.put(2018, cases18);
            sumPerYearMap.put(2019, cases19);

        return sumPerYearMap;
    };

    //Create a new list with the Pahang(Total) details
    private Function<List<Area>, List<Area>> createNewAreaList = (dataSource) -> {
        //Deep clone to avoid appending the dataSource accidentally
        List<Area> fullAreaList = listCloner.cloneList(dataSource.iterator());
        //Add a new Area object in the clonedList
        fullAreaList.add(new Area(  
                "Pahang(Total)",
                createSumPerYearMap.apply(
                        calcSumForAYear.apply(dataSource, 2014),
                        calcSumForAYear.apply(dataSource, 2015),
                        calcSumForAYear.apply(dataSource, 2016),
                        calcSumForAYear.apply(dataSource, 2017),
                        calcSumForAYear.apply(dataSource, 2018),
                        calcSumForAYear.apply(dataSource, 2019))
        ));
        return fullAreaList;
    };
    
    
    /****************GUI*******************/
    /****************Question 1*******************/
    private void bindAllDengueCasesDataToTable(List<Area> areaList) {
        //Get the table model 
        DefaultTableModel model = (DefaultTableModel) tbl_all_dengue_cases.getModel();
        
        //Add row into the table 
        areaList.stream().forEach((area) -> 
        {
            model.addRow(
                Stream.concat(
                    Arrays.stream(new Object[]{area.getName()}),
                    Arrays.stream(area.getCasesList().values().toArray())
                ).toArray(Object[]::new)
            );
        });
        
        //Highlight the last row of the table
        tbl_all_dengue_cases.addRowSelectionInterval(11, 11);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        btn_allCases = new javax.swing.JPanel();
        lbl_allCases_icon = new javax.swing.JLabel();
        lbl_allCases = new javax.swing.JLabel();
        btn_areaCases = new javax.swing.JPanel();
        lbl_areaCases_icon = new javax.swing.JLabel();
        lbl_areaCases = new javax.swing.JLabel();
        sprt_mainTitle = new javax.swing.JSeparator();
        lbl_mainTitle = new javax.swing.JLabel();
        panel_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jsp_all_dengue_cases = new javax.swing.JScrollPane();
        tbl_all_dengue_cases = new javax.swing.JTable();
        lbl_closeBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panel_bg.setBackground(new java.awt.Color(247, 247, 247));
        panel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(54, 33, 89));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_allCases.setBackground(new java.awt.Color(85, 65, 118));

        lbl_allCases_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_allCases_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/Cases_Icon.png"))); // NOI18N

        lbl_allCases.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_allCases.setForeground(new java.awt.Color(255, 255, 255));
        lbl_allCases.setText("All Dengue Cases");

        javax.swing.GroupLayout btn_allCasesLayout = new javax.swing.GroupLayout(btn_allCases);
        btn_allCases.setLayout(btn_allCasesLayout);
        btn_allCasesLayout.setHorizontalGroup(
            btn_allCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_allCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_allCases_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_allCases)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        btn_allCasesLayout.setVerticalGroup(
            btn_allCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_allCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_allCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_allCases)
                    .addComponent(lbl_allCases_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_menu.add(btn_allCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, -1));

        btn_areaCases.setBackground(new java.awt.Color(64, 43, 100));
        btn_areaCases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_areaCasesMouseClicked(evt);
            }
        });

        lbl_areaCases_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_areaCases_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/PinPoint_Icon.png"))); // NOI18N

        lbl_areaCases.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_areaCases.setForeground(new java.awt.Color(255, 255, 255));
        lbl_areaCases.setText("Dengue Cases per Area");

        javax.swing.GroupLayout btn_areaCasesLayout = new javax.swing.GroupLayout(btn_areaCases);
        btn_areaCases.setLayout(btn_areaCasesLayout);
        btn_areaCasesLayout.setHorizontalGroup(
            btn_areaCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_areaCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_areaCases_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_areaCases)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_areaCasesLayout.setVerticalGroup(
            btn_areaCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_areaCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_areaCases)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_areaCases_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_menu.add(btn_areaCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, -1));

        sprt_mainTitle.setPreferredSize(new java.awt.Dimension(50, 5));
        sprt_mainTitle.setRequestFocusEnabled(false);
        panel_menu.add(sprt_mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, 180, 10));

        lbl_mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mainTitle.setText("Dengue Report");
        panel_menu.add(lbl_mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 10, -1, -1));

        panel_bg.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 221, 480));

        panel_title.setBackground(new java.awt.Color(110, 89, 222));

        lbl_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("All Dengue Cases from 2014-2019");
        lbl_title.setToolTipText("");

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_title)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_title)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel_bg.add(panel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 35, 690, 80));

        jsp_all_dengue_cases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jsp_all_dengue_cases.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jsp_all_dengue_cases.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tbl_all_dengue_cases.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tbl_all_dengue_cases.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_all_dengue_cases.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tbl_all_dengue_cases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area", "2014", "2015", "2016", "2017", "2018", "2019"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_all_dengue_cases.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_all_dengue_cases.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_all_dengue_cases.setRowHeight(25);
        tbl_all_dengue_cases.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tbl_all_dengue_cases.setShowGrid(true);
        jsp_all_dengue_cases.setViewportView(tbl_all_dengue_cases);
        if (tbl_all_dengue_cases.getColumnModel().getColumnCount() > 0) {
            tbl_all_dengue_cases.getColumnModel().getColumn(0).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(1).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(2).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(3).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(4).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(4).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(5).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(5).setPreferredWidth(10);
            tbl_all_dengue_cases.getColumnModel().getColumn(6).setResizable(false);
            tbl_all_dengue_cases.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        panel_bg.add(jsp_all_dengue_cases, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 650, 325));

        lbl_closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_closeBtn.setForeground(new java.awt.Color(54, 33, 89));
        lbl_closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_closeBtn.setText("X");
        lbl_closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_closeBtnMousePressed(evt);
            }
        });
        panel_bg.add(lbl_closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(906, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeBtnMousePressed
        //Exit button
        System.exit(0);
    }//GEN-LAST:event_lbl_closeBtnMousePressed

    private void btn_areaCasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_areaCasesMouseClicked
        //Direct to next page
        GUISecondPage secondPage = new GUISecondPage(orgDataSource,newAreaList);
        secondPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_areaCasesMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //Draggable
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX-mousepX,coordinateY-mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Draggable - get X and Y 
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_allCases;
    private javax.swing.JPanel btn_areaCases;
    private javax.swing.JScrollPane jsp_all_dengue_cases;
    private javax.swing.JLabel lbl_allCases;
    private javax.swing.JLabel lbl_allCases_icon;
    private javax.swing.JLabel lbl_areaCases;
    private javax.swing.JLabel lbl_areaCases_icon;
    private javax.swing.JLabel lbl_closeBtn;
    private javax.swing.JLabel lbl_mainTitle;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_title;
    private javax.swing.JSeparator sprt_mainTitle;
    private javax.swing.JTable tbl_all_dengue_cases;
    // End of variables declaration//GEN-END:variables

    
}
